# Multivariate Community Analysis

Know more details of the aftermentioned statistical methods to see [@xia2018statistical].

## Multivariate homogeneity of groups dispersions (variances)

[@anderson2006multivariate]

```{r, warning=FALSE, message=FALSE}
data("enterotypes_arumugam")
run_betadisper(enterotypes_arumugam, variable = "Enterotype", method = "bray")
```


## Permutational Multivariate Analysis of Variance (PERMANOVA)

[@anderson2014permutational]
```{r, warning=FALSE, message=FALSE}
run_PERMANOVA(enterotypes_arumugam, method = "bray")
```

## Mantel Test (MANTEL)

[@mantel1967detection]
```{r, warning=FALSE, message=FALSE}
run_MANTEL(enterotypes_arumugam,
           y_variables = c("Enterotype", "Clinical.Status"),
           z_variables = c("Nationality", "Gender"),
           norm = FALSE,
           method = "mantel.partial",
           method_dist = c("bray", "euclidean", "jaccard"))
```


## Analysis of Similarity (ANOSIM)

[@clarke1993non]
```{r, warning=FALSE, message=FALSE}
run_ANOSIM(enterotypes_arumugam, variable = "Enterotype", method = "bray")
```

## Multi-response Permutation Procedures (MRPP)

[@mielke1991application]
```{r, warning=FALSE, message=FALSE}
run_MRPP(enterotypes_arumugam, variable = "Enterotype", method = "bray")
```
